global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'f1r3node'
    static_configs:
      - targets:
          - 'rnode.bootstrap:40403'
          - 'rnode.validator1:40403'
          - 'rnode.validator2:40403'
          - 'rnode.validator3:40403'
          - 'rnode.readonly:40403'
        labels:
          shard: 'default'
    metrics_path: /metrics
